apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-minio-pvc4
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
  storageClassName: standard 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-minio-deployment
spec:
  selector:
    matchLabels:
      app: mlflow-minio
  template:
    metadata:
      labels:
        app: mlflow-minio
    spec:
      volumes:
      - name: mlflow-minio-storage
        persistentVolumeClaim:
          claimName: mlflow-minio-pvc4
      containers:
      - name: mlflow-minio
        image: minio/minio:RELEASE.2020-10-18T21-54-12Z
        args:
        - server
        - /data
        volumeMounts:
        - name: mlflow-minio-storage
          mountPath: '/data'
        env:
        - name: MINIO_ROOT_USER
          value: "tytH73367"
        - name: MINIO_ROOT_PASSWORD
          value: "HGhygs12_"
        ports:
        - containerPort: 9000
          hostPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-minio-service
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: mlflow-minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-minio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.il/add-base-url: "true"
    nginx.ingress.kubernetes.il/ssl-redirect: "false"
spec:
  rules:
  - host: mlflow-minio.local
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: mlflow-minio-service
            port:
              number: 9000